Fix bug in circular inclusion detection
Following commit cbdf622b6172 ("Fix bug #424 Wrong circular inclusion
detection."), we've experienced issues with Sphinx's spell checker,
which crashes for Cilium docs with the following error:

    IndexError: pop from empty list

and a traceback pointing to self.document.include_log.pop(). Let's make
sure we don't attempt to pop() if the list is empty.

Fixes: cbdf622b6172 ("Fix bug #424 Wrong circular inclusion detection.")
Signed-off-by: Quentin Monnet <quentin@isovalent.com>